### ISSUE TITLE
Establishing a tunnel via proxy server failed

### ISSUE THREAD

**Issue by inovamatic** [voryx/angular-wamp#68] opened 2017-09-26 19:49 UTC
Hello,

I have a webapp in production with a crossbar io server and we connect to it using autobahn js and angular-wamp.
The crossbar io has 2 websockets transports, no web.
When an android device is connected through wifi all works fine.
When it connects via LTE depends on the provider.
Vodafone mobile connected devices give a "failed: Establishing a tunnel via proxy server failed." error.
One the other 2 Portuguese moblie providers all goes smooth.

Any suggestions of might be the problem? Anyone knows a solution?
Thanks

**Comment by davidwdan** [comment] 2017-09-26 19:52
This is a duplicate of https://github.com/crossbario/autobahn-js/issues/320
I'm going to close this and answer you over there.

**Closed as completed by davidwdan** 2017-09-26 19:52 UTC
